// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Creator struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type NewShort struct {
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Category    string         `json:"category"`
	File        graphql.Upload `json:"file"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
}

type Short struct {
	ID          int      `json:"id"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	FileURL     string   `json:"fileUrl"`
	Creator     *Creator `json:"creator"`
}
